services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py test &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local
#    depends_on:
#      - pgdb
#
#  pgdb:
#    image: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    expose:
#      - 5432
#    env_file:
#      - .env.local
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U your_user -d your_test_db" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#volumes:
#  postgres_data:
