services:
  django:
    build: .
    container_name: django
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py test &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

#    volumes:
#      - .:/usr/src/app
#    depends_on:
#      - pgdb

#  pgdb:
#    image: postgres
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#
#    container_name: pgdb
#    volumes:
#      - pgdbdata:/var/lib/postgresql/data
#
#volumes:
#  pgdbdata: null
